language: objective-c
os: osx

# Install Strap and then test installing packages works.
script:
- brew update
- cd Formula && for i in *; do brew install $i; brew uninstall $i; done
- cd ../Casks && for i in *; do brew cask install $i; brew cask uninstall $i; done
